id = "xml"
name = "XML"
description = "XML syntax support."
version = "0.1.0"
schema_version = 1
authors = ["sweetppro"]
repository = "https://github.com/sweetppro/zed-xml"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
commit = "5000ae8f22d11fbe93939b05c1e37cf21117162d"
path = "xml"
